[tool.poetry]
name = "fetchai-babble"
version = "0.1.1"
description = "A simple python library for interacting with the Fetch.ai messaging service (called Memorandum)"
authors = ["Fetch.AI Limited"]
license = "Apache 2.0"
readme = "README.md"
packages = [{ include = "babble", from = "src" }]


[tool.poetry.dependencies]
python = "^3.7"
ecdsa = "^0.18.0"
requests = "^2.28.2"
bech32 = "^1.2.0"
pycryptodome = "^3.16.0"
pyjwt = "^2.6.0"
eciespy = "^0.3.13"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
black = "22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
